apiVersion: v1
kind: Pod
metadata:
  name: mynginx1
  labels:
    devops: '18'
    company: talent
  namespace: prod  # Corrected indentation here
spec:
  containers:
  - name: nginx18
    image: nginx:1.19.1
    ports:
    - containerPort: 80

